/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import image_management.ImageFilters;
import image_management.ImageManager;
import image_management.ImageTrans;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import org.opencv.core.Core;
import org.opencv.core.Mat;

/**
 *
 * @author devel
 */
public class VisualMain extends javax.swing.JFrame {

    //vairables 
    private static int lb_widht;
    private static int lb_height;
    private static int lbo_widht;
    private static int lbo_height;
    ImageManager my_img_manager;
    int previo_br, previo_ct, previo_gm, previo_averg = 0;
    int actual_br, actual_ct, actual_gm, actual_averg = 0;
    public Mat mat_current;
    public byte[] byte_current;
    public Mat mat_last;
    public byte[] byte_last;

    /**
     * Creates new form NewJFrame
     */
    public VisualMain() {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        my_img_manager = new ImageManager();
        initComponents();
        lb_widht = lb_img_edit.getWidth();
        lb_height = lb_img_edit.getHeight();
        lbo_widht = lb_img_orig.getWidth();
        lbo_height = lb_img_orig.getHeight();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_img_orig = new javax.swing.JLabel();
        lb_img_edit = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bt_Load_Img = new javax.swing.JButton();
        bt_Reset_Img = new javax.swing.JButton();
        bt_Save_Img = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Corrections = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        slider_bright = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        slider_gamma = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        slider_constrast = new javax.swing.JSlider();
        Check_Neg = new javax.swing.JCheckBox();
        Check_Bin = new javax.swing.JCheckBox();
        Smoothing = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        slider_averging = new javax.swing.JSlider();
        jPanel8 = new javax.swing.JPanel();
        slider_gaussian = new javax.swing.JSlider();
        jPanel10 = new javax.swing.JPanel();
        slider_median = new javax.swing.JSlider();
        Transformations = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        slider_scala = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_img_orig.setBorder(javax.swing.BorderFactory.createTitledBorder("Original"));

        lb_img_edit.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen:"));

        bt_Load_Img.setText("Cargar Imagen");
        bt_Load_Img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Load_ImgMouseClicked(evt);
            }
        });

        bt_Reset_Img.setText("Reset");
        bt_Reset_Img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Reset_ImgMouseClicked(evt);
            }
        });

        bt_Save_Img.setText("Guardar");
        bt_Save_Img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_Save_ImgMouseClicked(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Brillo"));

        slider_bright.setMajorTickSpacing(1);
        slider_bright.setMaximum(10);
        slider_bright.setMinimum(-10);
        slider_bright.setMinorTickSpacing(1);
        slider_bright.setPaintTicks(true);
        slider_bright.setSnapToTicks(true);
        slider_bright.setToolTipText("");
        slider_bright.setValue(0);
        slider_bright.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_brightStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_bright, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_bright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gamma"));

        slider_gamma.setMajorTickSpacing(1);
        slider_gamma.setMaximum(10);
        slider_gamma.setMinorTickSpacing(1);
        slider_gamma.setPaintTicks(true);
        slider_gamma.setSnapToTicks(true);
        slider_gamma.setToolTipText("");
        slider_gamma.setValue(0);
        slider_gamma.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_gammaStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_gamma, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(slider_gamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraste"));

        slider_constrast.setMajorTickSpacing(1);
        slider_constrast.setMaximum(10);
        slider_constrast.setMinimum(-10);
        slider_constrast.setMinorTickSpacing(1);
        slider_constrast.setPaintTicks(true);
        slider_constrast.setToolTipText("");
        slider_constrast.setValue(0);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_constrast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_constrast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Check_Neg.setText("Negativo");

        Check_Bin.setText("Binario");

        javax.swing.GroupLayout CorrectionsLayout = new javax.swing.GroupLayout(Corrections);
        Corrections.setLayout(CorrectionsLayout);
        CorrectionsLayout.setHorizontalGroup(
            CorrectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorrectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CorrectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CorrectionsLayout.createSequentialGroup()
                        .addGroup(CorrectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CorrectionsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Check_Neg)
                                .addGap(18, 18, 18)
                                .addComponent(Check_Bin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CorrectionsLayout.setVerticalGroup(
            CorrectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorrectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CorrectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check_Neg)
                    .addComponent(Check_Bin))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Corrections", Corrections);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Averging"));

        slider_averging.setMajorTickSpacing(1);
        slider_averging.setMaximum(10);
        slider_averging.setMinorTickSpacing(1);
        slider_averging.setPaintTicks(true);
        slider_averging.setSnapToTicks(true);
        slider_averging.setToolTipText("");
        slider_averging.setValue(0);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_averging, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(slider_averging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Gaussian"));

        slider_gaussian.setMajorTickSpacing(1);
        slider_gaussian.setMaximum(10);
        slider_gaussian.setMinorTickSpacing(1);
        slider_gaussian.setPaintTicks(true);
        slider_gaussian.setSnapToTicks(true);
        slider_gaussian.setToolTipText("");
        slider_gaussian.setValue(0);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_gaussian, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(slider_gaussian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Median"));

        slider_median.setMajorTickSpacing(1);
        slider_median.setMaximum(10);
        slider_median.setMinorTickSpacing(1);
        slider_median.setPaintTicks(true);
        slider_median.setSnapToTicks(true);
        slider_median.setToolTipText("");
        slider_median.setValue(0);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_median, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(slider_median, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout SmoothingLayout = new javax.swing.GroupLayout(Smoothing);
        Smoothing.setLayout(SmoothingLayout);
        SmoothingLayout.setHorizontalGroup(
            SmoothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmoothingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SmoothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SmoothingLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SmoothingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(SmoothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        SmoothingLayout.setVerticalGroup(
            SmoothingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmoothingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Smooothing", Smoothing);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Escala"));

        slider_scala.setMajorTickSpacing(1);
        slider_scala.setMaximum(10);
        slider_scala.setMinorTickSpacing(1);
        slider_scala.setPaintTicks(true);
        slider_scala.setSnapToTicks(true);
        slider_scala.setToolTipText("");
        slider_scala.setValue(0);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider_scala, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(slider_scala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout TransformationsLayout = new javax.swing.GroupLayout(Transformations);
        Transformations.setLayout(TransformationsLayout);
        TransformationsLayout.setHorizontalGroup(
            TransformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransformationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TransformationsLayout.setVerticalGroup(
            TransformationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransformationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transformations", Transformations);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_Load_Img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Reset_Img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bt_Save_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_img_orig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_img_edit, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_img_orig, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Load_Img)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_Reset_Img)
                            .addComponent(bt_Save_Img))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Load_ImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Load_ImgMouseClicked
        // TODO add your handling code here:
        try {
            mat_current = my_img_manager.loadImage();
            byte_current = ImageManager.toBytes(mat_current);
        } catch (Exception e) {
            System.out.println("Error al cargar la imagen");
        } finally {
            setUp(mat_current, byte_current);
        }
    }//GEN-LAST:event_bt_Load_ImgMouseClicked

    private void bt_Reset_ImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Reset_ImgMouseClicked
        // TODO add your handling code here:
        restart();
    }//GEN-LAST:event_bt_Reset_ImgMouseClicked

    private void bt_Save_ImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_Save_ImgMouseClicked
        // TODO add your handling code here:
        try {
            int var = 0;
            JFileChooser chooser = new JFileChooser("D:/Escritorio");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.showDialog(null, null);
            try {
                File outpufile = new File(chooser.getSelectedFile().toString() + "/image_" + var + ".jpg");
                while (outpufile.exists()) {
                    var++;
                    outpufile = new File(chooser.getSelectedFile().toString() + "/image_" + var + ".jpg");
                }
                ImageIO.write(ImageManager.toRenderedImage((BufferedImage) ImageManager.toBufferedImage(mat_last, byte_last)), "jpg", outpufile);
            } catch (IOException ex) {
                System.out.println("Error al guardar la Imagen");
            }
        } catch (HeadlessException ex) {
        }
    }//GEN-LAST:event_bt_Save_ImgMouseClicked

    private void slider_brightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_brightStateChanged
        // TODO add your handling code here:
        Mat e_mat = null;
        byte[] e_byte = null;
        actual_br = slider_bright.getValue();
        try {
            if (actual_br > previo_br) {
                e_mat = ImageFilters.addBrightness(byte_current, mat_current, actual_br);
                e_byte = ImageManager.toBytes(e_mat);
            } else {
                e_mat = ImageFilters.lessBrightness(byte_current, mat_current, previo_br);
                e_byte = ImageManager.toBytes(e_mat);
            }
        } catch (Exception e) {
            System.out.println("Error al aplicar brillo");
        } finally {
            changeImg(e_mat, e_byte);
        }
        mat_current = e_mat;
        byte_current = e_byte;
    }//GEN-LAST:event_slider_brightStateChanged

    private void slider_gammaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_gammaStateChanged
        // TODO add your handling code here:
        Mat e_mat = null;
        byte[] e_byte = null;
        actual_gm = slider_gamma.getValue();
        try {
//            e_mat = ImageFilters.addGamma(byte_current, mat_current, actual_gm);
//            e_byte = ImageManager.toBytes(e_mat);
//            previo_gm = actual_gm;
            if (actual_gm > previo_gm) {
                e_mat = ImageFilters.addGamma(byte_current, mat_current, actual_gm);
                e_byte = ImageManager.toBytes(e_mat);
                previo_gm = actual_gm;
            } else {

            }
        } catch (Exception e) {
            System.out.println("Error al aplicar gamma");
        } finally {
            changeImg(e_mat, e_byte);
        }
        mat_current = e_mat;
        byte_current = e_byte;
    }//GEN-LAST:event_slider_gammaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_Bin;
    private javax.swing.JCheckBox Check_Neg;
    private javax.swing.JPanel Corrections;
    private javax.swing.JPanel Smoothing;
    private javax.swing.JPanel Transformations;
    private javax.swing.JButton bt_Load_Img;
    private javax.swing.JButton bt_Reset_Img;
    private javax.swing.JButton bt_Save_Img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_img_edit;
    private javax.swing.JLabel lb_img_orig;
    private javax.swing.JSlider slider_averging;
    private javax.swing.JSlider slider_bright;
    private javax.swing.JSlider slider_constrast;
    private javax.swing.JSlider slider_gamma;
    private javax.swing.JSlider slider_gaussian;
    private javax.swing.JSlider slider_median;
    private javax.swing.JSlider slider_scala;
    // End of variables declaration//GEN-END:variables

    private void setUp(Mat m, byte[] b) {
        try {
            lb_img_edit.setSize(lb_widht, lb_height);
            lb_img_orig.setSize(lbo_widht, lbo_height);
            Image img = ImageManager.toBufferedImage(m, b);
            lb_img_edit.setIcon(new ImageIcon(img.getScaledInstance(lb_img_edit.getWidth(), lb_img_edit.getHeight(),
                    Image.SCALE_DEFAULT)));
            lb_img_orig.setIcon(new ImageIcon(img.getScaledInstance(lb_img_orig.getWidth(), lb_img_orig.getHeight(),
                    Image.SCALE_DEFAULT)));
        } catch (Exception e) {
        }
    }

    private void restart() {
        try {
            mat_current = ImageManager.loadImageDir();
            byte_current = ImageManager.toBytes(mat_current);
            setUp(mat_current, byte_current);
        } catch (Exception e) {
        }
    }

    private void changeImg(Mat m, byte[] b) {
        try {
            lb_img_edit.setSize(lb_widht, lb_height);
            Image img = ImageManager.toBufferedImage(m, b);
            lb_img_edit.setIcon(new ImageIcon(img.getScaledInstance(lb_img_edit.getWidth(), lb_img_edit.getHeight(),
                    Image.SCALE_DEFAULT)));
        } catch (Exception e) {
        }

    }
}
